### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by HendrikF** [infogulch/pyspades-events#2]
Hello infogulch,
i'm thinking about using this in a little project, since it is very clever and scripts can be un/loaded on the fly.
Under which license are you releasing it? MIT? GPL? BSD?

**Comment by infogulch** [comment]
Thanks for reminding me that I hadn't licenced this yet. I hope you find it useful! 

I'd enjoy knowing a bit about the project where you're using this, if/when you feel comfortable! I would also be happy to accept changes or answer questions if you have any!
