### ISSUE TITLE
How continue?

### ISSUE THREAD

**Issue by HendrikF** [infogulch/pyspades-events#3]
Hi @infogulch ,

Our game server has nearly the same structure like pyspades, except that we dont use twisted.
Now our problem is, that all scripts have to share data, like the game map, players, scores, ... How can we achieve this when using such core scripts?

How would you continue with your event system and implement it in pyspades (theoretical)?

I am looking forward to hearing from you soon, because you didn't respond to the email address provided by github...
Feel free to respond to my email.

Greets, Hendrik.

**Comment by infogulch** [comment]
Hi HendrikF. Did anything ever come of our email conversation? Were you able to implement your system fully?

**Comment by HendrikF** [comment]
Hi,
yes you answered on 1st June 2015.
We were not able to work on the project, because we both started studying and we also don't have a plan, how to implement the time synchronization between the client and the server. Unfortunately we didn't even have time to think about solutions because of university and so we paused work on the project completely.
I think, that we will continue some day, but I am looking for someone experienced in this field ;)

**Comment by infogulch** [comment]
Well I wish you luck on your project. :)
